# Default values for busybox.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: docker.artifactory.globoi.com/backoffice/k8s-tools
  tag: '1.0'
  pullPolicy: Always

service:
  port: '80'

env: 
  http_proxy: http://proxy-sa-e1.gcp.i.globo:3128
  https_proxy: http://proxy-sa-e1.gcp.i.globo:3128
  HTTP_PROXY: http://proxy-sa-e1.gcp.i.globo:3128
  HTTPS_PROXY: http://proxy-sa-e1.gcp.i.globo:3128
  NO_PROXY: .gcp.i.globo,.globoi.com,localhost
  no_proxy: .gcp.i.globo,.globoi.com,localhost